/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StoreUserRequest } from '../../models/store-user-request';
import { UserResource } from '../../models/user-resource';

export interface UsersStore$Params {
      body: StoreUserRequest
}

export function usersStore(http: HttpClient, rootUrl: string, params: UsersStore$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data': UserResource;
}>> {
  const rb = new RequestBuilder(rootUrl, usersStore.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data': UserResource;
      }>;
    })
  );
}

usersStore.PATH = '/users';
