/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateUserRequest } from '../../models/update-user-request';
import { UserResource } from '../../models/user-resource';

export interface UsersUpdate$Params {

/**
 * The user ID
 */
  user: number;
      body: UpdateUserRequest
}

export function usersUpdate(http: HttpClient, rootUrl: string, params: UsersUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data': UserResource;
}>> {
  const rb = new RequestBuilder(rootUrl, usersUpdate.PATH, 'put');
  if (params) {
    rb.path('user', params.user, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data': UserResource;
      }>;
    })
  );
}

usersUpdate.PATH = '/users/{user}';
