/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserResource } from '../../models/user-resource';

export interface UsersIndex$Params {
}

export function usersIndex(http: HttpClient, rootUrl: string, params?: UsersIndex$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data': Array<UserResource>;
}>> {
  const rb = new RequestBuilder(rootUrl, usersIndex.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data': Array<UserResource>;
      }>;
    })
  );
}

usersIndex.PATH = '/users';
