/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SendResetPasswordMailRequest } from '../../models/send-reset-password-mail-request';

export interface AuthForgotPassword$Params {
      body: SendResetPasswordMailRequest
}

export function authForgotPassword(http: HttpClient, rootUrl: string, params: AuthForgotPassword$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'message': (null | Array<any> | string);
}>> {
  const rb = new RequestBuilder(rootUrl, authForgotPassword.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'message': (null | Array<any> | string);
      }>;
    })
  );
}

authForgotPassword.PATH = '/auth/forgot-password';
