/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryResource } from '../../models/category-resource';

export interface CategoriesShow$Params {

/**
 * The category ID
 */
  category: number;
}

export function categoriesShow(http: HttpClient, rootUrl: string, params: CategoriesShow$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data': CategoryResource;
}>> {
  const rb = new RequestBuilder(rootUrl, categoriesShow.PATH, 'get');
  if (params) {
    rb.path('category', params.category, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data': CategoryResource;
      }>;
    })
  );
}

categoriesShow.PATH = '/categories/{category}';
