/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryResource } from '../../models/category-resource';

export interface CategoriesIndex$Params {
}

export function categoriesIndex(http: HttpClient, rootUrl: string, params?: CategoriesIndex$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data': Array<CategoryResource>;
}>> {
  const rb = new RequestBuilder(rootUrl, categoriesIndex.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data': Array<CategoryResource>;
      }>;
    })
  );
}

categoriesIndex.PATH = '/categories';
