/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryResource } from '../../models/category-resource';
import { StoreCategoryRequest } from '../../models/store-category-request';

export interface CategoriesStore$Params {
      body: StoreCategoryRequest
}

export function categoriesStore(http: HttpClient, rootUrl: string, params: CategoriesStore$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data': CategoryResource;
}>> {
  const rb = new RequestBuilder(rootUrl, categoriesStore.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data': CategoryResource;
      }>;
    })
  );
}

categoriesStore.PATH = '/categories';
