/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransactionResource } from '../../models/transaction-resource';
import { UpdateTransactionRequest } from '../../models/update-transaction-request';

export interface TransactionsUpdate$Params {

/**
 * The transaction ID
 */
  transaction: number;
      body: UpdateTransactionRequest
}

export function transactionsUpdate(http: HttpClient, rootUrl: string, params: TransactionsUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data': TransactionResource;
}>> {
  const rb = new RequestBuilder(rootUrl, transactionsUpdate.PATH, 'put');
  if (params) {
    rb.path('transaction', params.transaction, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data': TransactionResource;
      }>;
    })
  );
}

transactionsUpdate.PATH = '/transactions/{transaction}';
