/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StoreTransactionRequest } from '../../models/store-transaction-request';
import { TransactionResource } from '../../models/transaction-resource';

export interface TransactionsStore$Params {
      body: StoreTransactionRequest
}

export function transactionsStore(http: HttpClient, rootUrl: string, params: TransactionsStore$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data': TransactionResource;
}>> {
  const rb = new RequestBuilder(rootUrl, transactionsStore.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data': TransactionResource;
      }>;
    })
  );
}

transactionsStore.PATH = '/transactions';
