/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AuthLogout$Params {
}

export function authLogout(http: HttpClient, rootUrl: string, params?: AuthLogout$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'message': (null | Array<any> | string);
}>> {
  const rb = new RequestBuilder(rootUrl, authLogout.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'message': (null | Array<any> | string);
      }>;
    })
  );
}

authLogout.PATH = '/auth/logout';
