/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface VerificationVerify$Params {
  id: number;
  hash: string;
}

export function verificationVerify(http: HttpClient, rootUrl: string, params: VerificationVerify$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'message': (null | Array<any> | string);
}>> {
  const rb = new RequestBuilder(rootUrl, verificationVerify.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('hash', params.hash, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'message': (null | Array<any> | string);
      }>;
    })
  );
}

verificationVerify.PATH = '/email/verify/{id}/{hash}';
