/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentResource } from '../../models/document-resource';
import { StoreDocumentRequest } from '../../models/store-document-request';

export interface DocumentsStore$Params {
      body: StoreDocumentRequest
}

export function documentsStore(http: HttpClient, rootUrl: string, params: DocumentsStore$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data': DocumentResource;
}>> {
  const rb = new RequestBuilder(rootUrl, documentsStore.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data': DocumentResource;
      }>;
    })
  );
}

documentsStore.PATH = '/documents';
