/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentResource } from '../../models/document-resource';
import { UpdateDocumentRequest } from '../../models/update-document-request';

export interface DocumentsUpdate$Params {

/**
 * The document ID
 */
  document: number;
      body: UpdateDocumentRequest
}

export function documentsUpdate(http: HttpClient, rootUrl: string, params: DocumentsUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data': DocumentResource;
}>> {
  const rb = new RequestBuilder(rootUrl, documentsUpdate.PATH, 'put');
  if (params) {
    rb.path('document', params.document, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data': DocumentResource;
      }>;
    })
  );
}

documentsUpdate.PATH = '/documents/{document}';
