/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentResource } from '../../models/document-resource';

export interface DocumentsIndex$Params {
  start_date?: (string | null);
  end_date?: (string | null);
  per_page?: (number | null);
}

export function documentsIndex(http: HttpClient, rootUrl: string, params?: DocumentsIndex$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data': Array<DocumentResource>;
}>> {
  const rb = new RequestBuilder(rootUrl, documentsIndex.PATH, 'get');
  if (params) {
    rb.query('start_date', params.start_date, {});
    rb.query('end_date', params.end_date, {});
    rb.query('per_page', params.per_page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data': Array<DocumentResource>;
      }>;
    })
  );
}

documentsIndex.PATH = '/documents';
