/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentResource } from '../../models/document-resource';

export interface DocumentsShow$Params {

/**
 * The document ID
 */
  document: number;
}

export function documentsShow(http: HttpClient, rootUrl: string, params: DocumentsShow$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data': DocumentResource;
}>> {
  const rb = new RequestBuilder(rootUrl, documentsShow.PATH, 'get');
  if (params) {
    rb.path('document', params.document, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data': DocumentResource;
      }>;
    })
  );
}

documentsShow.PATH = '/documents/{document}';
