/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BulkUpdateTransactionRequest {
  transactions: Array<{
'id': number;
'name': string;
'description'?: (string | null);
'date': string;
'value': number;
'category_id': number;
}>;
}
