/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryResource {
  created_at: (string | null);
  id: number;
  name: string;
  updated_at: (string | null);
}
