/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
export interface StoreUserRequest {
  email: string;
  name: string;
  password: string;
  password_confirmation: string;
  role?: Role;
}
