/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransactionResource {
  created_at: (string | null);
  date: string;
  description: (string | null);
  id: number;
  name: string;
  updated_at: (string | null);
  value: string;
}
