/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryResource } from '../models/category-resource';
export interface TransactionResource {
  category?: CategoryResource;
  created_at: (string | null);
  date: string;
  description: (string | null);
  id: number;
  name: string;
  updated_at: (string | null);
  value: string;
}
