/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTransactionRequest {
  category_id: number;
  date: string;
  description?: (string | null);
  name: string;
  value: number;
}
