/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
export interface UpdateUserRequest {
  email: string;
  name: string;
  password?: (string | null);
  password_confirmation?: (string | null);
  role?: Role;
}
